### PR TITLE
README: fix entrez example and document BLAST as not self contained

### PR DESCRIPTION
**Pull request by kortschak**
@ngoto Please take a look.

### CODE REVIEW

**Comment by kortschak** [comment]
If you want, I can link out to complete runnable examples within the repo.

**Comment by kortschak** [comment]
@ngoto, I have added links to compete runnable examples.

**Comment by ngoto** [comment]
I can run the two examples, but I need some try-and-error to find good working parameters (options) for the programs. Could you please write some runnable test parameters for the examples?

**Comment by kortschak** [comment]
```
~/src/github.com/biogo/ncbi $ go run paper/examples/fetch/fetch.go -email user@domain.tld -query "hemoglobin AND reptile" -out example.fa
2017/05/03 07:31:11 will retrieve 1 records.
2017/05/03 07:31:11 attempting to retrieve 500 records starting from 0 with 5 retries.
2017/05/03 07:31:12 retrieved records with 0 retries... writing out.
~/src/github.com/biogo/ncbi $ go run paper/examples/blast/blast.go -email user@domain.tld -prog blastp -query example.fa 
```

**Comment by kortschak** [comment]
*ping* @ngoto 

/cc @pjotrp

**Comment by pjotrp** [comment]
Best to bring the discussion back to the JOSS issue tracker.

**Comment by kortschak** [comment]
I'd need to get this accepted at least first.

**Comment by ngoto** [comment]
> ~/src/github.com/biogo/ncbi $ go run paper/examples/fetch/fetch.go -email user@domain.tld -query "hemoglobin AND reptile" -out example.fa

> ~/src/github.com/biogo/ncbi $ go run paper/examples/blast/blast.go -email user@domain.tld -prog blastp -query example.fa 

Could you please write the example usage in the head of each example source file?

**Comment by kortschak** [comment]
Please open a new issue for that, this PR has been merged.

**Comment by kortschak** [comment]
> Could you please write the example usage in the head of each example source file?

On further consideration, I don't see how this is possible in a way that will not mislead readers; the fetch example is standalone in that it requires no local file to run while the blast example requires a local file to submit to the blast server. Since the two programs are orthogonal, it does not seem sensible to have to cross reference fetch in the blast source since that misleads the user that that is the use case when it is not.

Further, the code in those programs are purely examples of use of a library, rather than stand alone applications that are intended to be used in production (though they could I guess). If the intention is to allow the user to test the functionality and correctness of the suite, then the test code for each of the packages already performs this.

**Comment by pjotrp** [comment]
@kortschak I am fine with this. You can close this issue as far as I am concerned.

**Pull request merged**
